[workspace]
members = [".", "ffi", "tools/runtime-bundler"]
resolver = "2"

[workspace.package]
version = "0.5.1"

[package]
name = "compukter-vm"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["rlib"]

[dependencies]
sha2 = { version = "0.10", default-features = false }

[profile.release]
codegen-units = 1
lto = "thin"
